
name: Update Data Daily

on:
  schedule:
    - cron: "0 6 * * *"  # codziennie o ~8:00 PL
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install libraries
        run: |
          pip install pandas yfinance requests

      - name: Run pipeline
        run: python pipeline.py

      - name: Commit new data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data.csv

          git commit -m "Update data.csv" || echo "No changes"

          git push
``
